FROM debian:10
ENV GOPATH=/go
ENV PATH=$GOPATH/bin:/usr/local/go/bin:$PATH

ARG GO_VERSION="1.23.4"

RUN apt-get update && apt-get install -y build-essential curl git sqlite3

RUN curl -OL https://go.dev/dl/go${GO_VERSION}.linux-amd64.tar.gz && \
      tar -C /usr/local -xzf go${GO_VERSION}.linux-amd64.tar.gz

WORKDIR /app

COPY . .

RUN go mod tidy && go build -o /release/sifeucr

VOLUME ["/release"]

CMD ["true"]
