// scripts/createSchema.go
package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strconv"
)

func main() {
	in := filepath.FromSlash("docs/schema.sql")
	out := filepath.FromSlash("config/schema_embed.go")

	data, err := os.ReadFile(in)
	if err != nil {
		panic(err)
	}

	src := fmt.Sprintf(`// Code generated by scripts/createSchema.go; DO NOT EDIT.

package config

// Schema is the SQL schema embedded at build time.
const schema = %s
`, strconv.Quote(string(data)))

	if err := os.WriteFile(out, []byte(src), 0o644); err != nil {
		panic(err)
	}
}
