// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
)

type Account struct {
	AccountID     int64
	AccountAbbr   string
	AccountName   string
	AccountActive bool
}

type ActiveAccount struct {
	AccountID     int64
	AccountAbbr   string
	AccountName   string
	AccountActive bool
}

type ActivePermission struct {
	PermissionID      int64
	PermissionUser    int64
	PermissionAccount int64
	PermissionInteger int64
	PermissionActive  bool
}

type ActiveUser struct {
	UserID     int64
	UserEmail  string
	UserName   string
	UserActive bool
}

type BudgetEntry struct {
	EntryID     int64
	EntryYear   int64
	EntryCode   int64
	EntryObject string
	EntryAmount float64
}

type Catalog struct {
	CatalogID       int64
	CatalogSupplier int64
	CatalogGrouping int64
	CatalogSummary  string
	CatalogTags     string
}

type Distribution struct {
	DistID        int64
	DistPeriod    int64
	DistEntryCode int64
	DistAccount   int64
	DistAmount    float64
	DistActive    bool
}

type DistributionModification struct {
	DistModID         int64
	DistModRequest    int64
	DistModDebitDist  int64
	DistModCreditDist int64
	DistModAmount     float64
	DistModLetter     string
}

type FullCatalog struct {
	CatalogID                int64
	CatalogSupplier          int64
	CatalogGrouping          int64
	CatalogSummary           string
	CatalogTags              string
	SupplierID               int64
	SupplierName             string
	SupplierEmail            string
	SupplierPhoneCountryCode int64
	SupplierPhone            int64
	SupplierLocation         string
}

type FullCatalogItem struct {
	ItemID                   int64
	ItemCatalog              int64
	ItemNumber               int64
	ItemSummary              string
	ItemDescription          string
	ItemAmount               float64
	CatalogID                int64
	CatalogSupplier          int64
	CatalogGrouping          int64
	CatalogSummary           string
	CatalogTags              string
	SupplierID               int64
	SupplierName             string
	SupplierEmail            string
	SupplierPhoneCountryCode int64
	SupplierPhone            int64
	SupplierLocation         string
}

type FullDistribution struct {
	DistID        int64
	DistPeriod    int64
	DistEntryCode int64
	DistAccount   int64
	DistAmount    float64
	DistActive    bool
	PeriodID      int64
	PeriodName    string
	PeriodStart   int64
	PeriodEnd     int64
	PeriodActive  bool
	EntryID       int64
	EntryYear     int64
	EntryCode     int64
	EntryObject   string
	EntryAmount   float64
	AccountID     int64
	AccountAbbr   string
	AccountName   string
	AccountActive bool
}

type FullPurchase struct {
	PurchaseID               int64
	PurchaseRequest          int64
	PurchaseRequired         int64
	PurchaseSupplier         int64
	PurchaseCurrency         string
	PurchaseExRateColones    float64
	PurchaseGrossAmount      float64
	PurchaseDiscount         float64
	PurchaseTaxRate          float64
	PurchaseGecoSol          string
	PurchaseGecoOrd          string
	PurchaseBill             string
	PurchaseTransfer         string
	PurchaseStatus           string
	ReqID                    int64
	ReqUser                  int64
	ReqAccount               int64
	ReqIssued                int64
	ReqDescr                 string
	ReqJustif                string
	UserID                   int64
	UserEmail                string
	UserName                 string
	UserActive               bool
	SupplierID               int64
	SupplierName             string
	SupplierEmail            string
	SupplierPhoneCountryCode int64
	SupplierPhone            int64
	SupplierLocation         string
}

type FullPurchaseBreakdown struct {
	BreakdownID           int64
	BreakdownPurchase     int64
	BreakdownItem         int64
	BreakdownQuantity     float64
	PurchaseID            int64
	PurchaseRequest       int64
	PurchaseRequired      int64
	PurchaseSupplier      int64
	PurchaseCurrency      string
	PurchaseExRateColones float64
	PurchaseGrossAmount   float64
	PurchaseDiscount      float64
	PurchaseTaxRate       float64
	PurchaseGecoSol       string
	PurchaseGecoOrd       string
	PurchaseBill          string
	PurchaseTransfer      string
	PurchaseStatus        string
	ItemID                int64
	ItemCatalog           int64
	ItemNumber            int64
	ItemSummary           string
	ItemDescription       string
	ItemAmount            float64
	CatalogID             int64
	CatalogSupplier       int64
	CatalogGrouping       int64
	CatalogSummary        string
	CatalogTags           string
}

type FullPurchaseSubscription struct {
	SubscriptionID           int64
	SubscriptionPurchase     int64
	SubscriptionUser         int64
	SubscriptionDist         int64
	SubscriptionIssued       int64
	SubscriptionGrossAmount  float64
	SubscriptionSignature    string
	SubscriptionSigned       bool
	SubscriptionActive       bool
	PurchaseID               int64
	PurchaseRequest          int64
	PurchaseRequired         int64
	PurchaseSupplier         int64
	PurchaseCurrency         string
	PurchaseExRateColones    float64
	PurchaseGrossAmount      float64
	PurchaseDiscount         float64
	PurchaseTaxRate          float64
	PurchaseGecoSol          string
	PurchaseGecoOrd          string
	PurchaseBill             string
	PurchaseTransfer         string
	PurchaseStatus           string
	UserID                   int64
	UserEmail                string
	UserName                 string
	UserActive               bool
	DistID                   int64
	DistPeriod               int64
	DistEntryCode            int64
	DistAccount              int64
	DistAmount               float64
	DistActive               bool
	ReqID                    int64
	ReqUser                  int64
	ReqAccount               int64
	ReqIssued                int64
	ReqDescr                 string
	ReqJustif                string
	EntryID                  int64
	EntryYear                int64
	EntryCode                int64
	EntryObject              string
	EntryAmount              float64
	AccountID                int64
	AccountAbbr              string
	AccountName              string
	AccountActive            bool
	PeriodID                 int64
	PeriodName               string
	PeriodStart              int64
	PeriodEnd                int64
	PeriodActive             bool
	SupplierID               int64
	SupplierName             string
	SupplierEmail            string
	SupplierPhoneCountryCode int64
	SupplierPhone            int64
	SupplierLocation         string
}

type GlobalModification struct {
	GlobalModID          int64
	GlobalModReq         int64
	GlobalModDebitEntry  sql.NullInt64
	GlobalModCreditEntry sql.NullInt64
	GlobalModAmount      float64
	GlobalModLetter      sql.NullString
}

type Item struct {
	ItemID          int64
	ItemCatalog     int64
	ItemNumber      int64
	ItemSummary     string
	ItemDescription string
	ItemAmount      float64
}

type Period struct {
	PeriodID     int64
	PeriodName   string
	PeriodStart  int64
	PeriodEnd    int64
	PeriodActive bool
}

type Permission struct {
	PermissionID      int64
	PermissionUser    int64
	PermissionAccount int64
	PermissionInteger int64
	PermissionActive  bool
}

type Purchase struct {
	PurchaseID            int64
	PurchaseRequest       int64
	PurchaseRequired      int64
	PurchaseSupplier      int64
	PurchaseCurrency      string
	PurchaseExRateColones float64
	PurchaseGrossAmount   float64
	PurchaseDiscount      float64
	PurchaseTaxRate       float64
	PurchaseGecoSol       string
	PurchaseGecoOrd       string
	PurchaseBill          string
	PurchaseTransfer      string
	PurchaseStatus        string
}

type PurchaseBreakdown struct {
	BreakdownID       int64
	BreakdownPurchase int64
	BreakdownItem     int64
	BreakdownQuantity float64
}

type PurchaseSubscription struct {
	SubscriptionID          int64
	SubscriptionPurchase    int64
	SubscriptionUser        int64
	SubscriptionDist        int64
	SubscriptionIssued      int64
	SubscriptionGrossAmount float64
	SubscriptionSignature   string
	SubscriptionSigned      bool
	SubscriptionActive      bool
}

type Request struct {
	ReqID      int64
	ReqUser    int64
	ReqAccount int64
	ReqIssued  int64
	ReqDescr   string
	ReqJustif  string
}

type RequestDoc struct {
	DocID       int64
	DocPurchase int64
	DocUrl      string
}

type Supplier struct {
	SupplierID               int64
	SupplierName             string
	SupplierEmail            string
	SupplierPhoneCountryCode int64
	SupplierPhone            int64
	SupplierLocation         string
}

type User struct {
	UserID     int64
	UserEmail  string
	UserName   string
	UserActive bool
}
